version: "2.1"

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest  # Image officielle LinuxServer.io pour Heimdall
    container_name: heimdall  # Nom générique du conteneur (évite "home1")

    environment:
      - PUID=1000            # UID de l'utilisateur local pour permissions
      - PGID=1000            # GID du groupe local
      - TZ=Etc/UTC           # Fuseau horaire à ajuster

    volumes:
      - /chemin/local/heimdall/config:/config  # Volume pour config persistante

    ports:
      - 10014:80            # Port HTTP exposé
      - 9443:443            # Port HTTPS exposé

    restart: unless-stopped  # Redémarrage automatique sauf arrêt manuel
